language: php

php:
  - '7.1'

sudo: enabled

branches:
  only:
    - master

script:
  - echo "There are no tests."

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: www.iaibai.com
    skip_cleanup: true
    region: eu-west-1
    on:
      branch: master
