language: php

php:
  - '7.1'

sudo: enabled

install:
  - composer install

jobs:
  include:
    - stage: test
      script: ./vendor/bin/phpunit
    - script: ./vendor/bin/phpcs -n --standard=PSR2 --colors src/
