language: php

php:
  - '7.1'

sudo: enabled

cache:
  directories:
    - vendor

install:
  - composer install

script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/phpcs -n --standard=PSR2 --colors src/

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key:
    secure: $SECRETACCESSKEY
  region: eu-west-1  
  app: "iaibai.co.uk"
  env: "iaibai-production"
  bucket_name: "elasticbeanstalk-eu-west-1-495135221592"
  on:
    branch: master
