version: 0.2
phases:
  install:
    commands:
      - npm install
  pre_build:
    commands:
      - echo running unit tests
      - npm run test
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo built!
